### ISSUE TITLE
neb publish on staging gives mysterious 504 error 

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-press#114]
Please see details in https://github.com/Connexions/nebuchadnezzar/issues/50

Typical error:
```
Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$ neb publish staging col11992 "changed astronaut to space pirate and author role"
unknown response:
  status: 504
  contents: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
Traceback (most recent call last):
  File "/usr/local/bin/neb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/main.py", line 330, in publish
    has_published = _publish(base_url, struct, publication_message)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/main.py", line 312, in _publish
    raise RuntimeError('unknown response, see output above')
RuntimeError: unknown response, see output above
```

When the '504' happens , the apparently successful publish actually put crap data in the database: in particular, it set a zero value for the license id. This is a showstopper for release.

**Comment by pumazi** [comment]
The plan is to attempt to fix this by writing the latency prone event handlers as asynchronous functions. To do this, we'll incorporate the Celery library as an easy way to obtain out-of-process asynchronous behavior. This will shorten the time to response, since the response will no longer be blocked by the latency prone event handlers.

**Comment by pumazi** [comment]
The deployment work for this is captured in Connexions/cnx-deploy#703 & Connexions/cnx-deploy#704 & Connexions/cnx-deploy#705

**Comment by Bkblodget** [comment]
Successfully published col11776 to qa.cnx without receiving 504 error - I got the "Great Work!" message. 

*side note:* the zip did not automatically enqueue upon publish

**Comment by Bkblodget** [comment]
Successfully published col12170 to qa.cnx without receiving 504 error.

**Comment by Bkblodget** [comment]
**passed**

successful neb publish of col11776 twice with no 504 error

**Comment by Bkblodget** [comment]
This bug may have returned :/ 

Received 504 when attempting to publish col24361, however the publish was still successful.

```
Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$ neb publish prod col24361 "batch-modified art exercise class"
unknown response:
  status: 504
  contents: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>


Traceback (most recent call last):
  File "/usr/local/bin/neb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/_common.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/publish.py", line 100, in publish
    has_published = _publish(base_url, struct, publication_message)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/publish.py", line 77, in _publish
    raise RuntimeError('unknown response, see output above')
RuntimeError: unknown response, see output above
Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$
 ```
