### ISSUE TITLE
Publishing a litezip with an encapsulation directory

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-press#19]
When publishing a litezip with an encapsulation directory, we run into an error.

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid_swagger/tween.py", line 193, in validator_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/app/press/views/publishing.py", line 41, in publish
    litezip_struct = parse_litezip(litezip_dir)
  File "/usr/local/lib/python3.6/site-packages/litezip/main.py", line 104, in parse_litezip
    struct = [parse_collection(path)]
  File "/usr/local/lib/python3.6/site-packages/litezip/main.py", line 87, in parse_collection
    raise MissingFile(file)
litezip.exceptions.MissingFile: /app/var/5mcb_2cv/collection.xml
```

**Comment by pumazi** [comment]
Basically I didn't account for an encapsulation directory on the litezip for some reason. The litezip, like a completezip, should have a top level structure that looks something like this completezip example:
```
> unzip -l complete.zip 
Archive:  complete.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  11-14-16 11:56   col11405_1.2_complete/
     7486  11-14-16 11:56   col11405_1.2_complete/collection.xml
        0  11-14-16 11:56   col11405_1.2_complete/m37154/
    13939  11-14-16 11:56   col11405_1.2_complete/m37154/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m37154/index.cnxml.html
    13929  11-14-16 11:56   col11405_1.2_complete/m37154/index_auto_generated.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m37217/
    19629  11-14-16 11:56   col11405_1.2_complete/m37217/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m37217/index.cnxml.html
    19619  11-14-16 11:56   col11405_1.2_complete/m37217/index_auto_generated.cnxml
    10273  11-14-16 11:56   col11405_1.2_complete/m37217/Lab4 Fill Order.png
    32230  11-14-16 11:56   col11405_1.2_complete/m37217/MSP430 Interrupt Execution.png
        0  11-14-16 11:56   col11405_1.2_complete/m37386/
    16251  11-14-16 11:56   col11405_1.2_complete/m37386/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m37386/index.cnxml.html
    16241  11-14-16 11:56   col11405_1.2_complete/m37386/index_auto_generated.cnxml
    31208  11-14-16 11:56   col11405_1.2_complete/m37386/MSP430 ADC10CTL0.png
    30150  11-14-16 11:56   col11405_1.2_complete/m37386/MSP430 ADC10CTL1.png
        0  11-14-16 11:56   col11405_1.2_complete/m40645/
     7228  11-14-16 11:56   col11405_1.2_complete/m40645/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m40645/index.cnxml.html
     7219  11-14-16 11:56   col11405_1.2_complete/m40645/index_auto_generated.cnxml
    10273  11-14-16 11:56   col11405_1.2_complete/m40645/Lab4 Fill Order.png
        0  11-14-16 11:56   col11405_1.2_complete/m40646/
    10661  11-14-16 11:56   col11405_1.2_complete/m40646/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m40646/index.cnxml.html
    10652  11-14-16 11:56   col11405_1.2_complete/m40646/index_auto_generated.cnxml
    21702  11-14-16 11:56   col11405_1.2_complete/m40646/Photodiode.png
        0  11-14-16 11:56   col11405_1.2_complete/m42303/
     7022  11-14-16 11:56   col11405_1.2_complete/m42303/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m42303/index.cnxml.html
     7008  11-14-16 11:56   col11405_1.2_complete/m42303/index_auto_generated.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m42304/
     3953  11-14-16 11:56   col11405_1.2_complete/m42304/index.cnxml
        0  11-14-16 11:56   col11405_1.2_complete/m42304/index.cnxml.html
     3938  11-14-16 11:56   col11405_1.2_complete/m42304/index_auto_generated.cnxml
 --------                   -------
   300611                   36 files```
Here the `col11405_1.2_complete` is the encapsulating directory.
