### ISSUE TITLE
Failed to publish col11740

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-press#48]
```
BritneyBlodget$ neb get col11740
Downloading col11740  [####################################]  100%             
Extracting col11740  [####################################]  100%
BritneyBlodget$ XXX_HOST="dev.cnx.org" neb publish col11740 "test"
unknown response:
  status: 503
  contents: <!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 98682</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

Traceback (most recent call last):
  File "/usr/local/bin/neb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/main.py", line 254, in publish
    has_published = _publish(struct, publication_message)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/main.py", line 240, in _publish
    raise RuntimeError('unknown response, see output above')
RuntimeError: unknown response, see output above
```

**Comment by pumazi** [comment]
I've been able to reproduce this. varnish says the following in logging:  ``--  FetchError     http first read error: EOF``. This is the type of message delivered by varnish when the connection times out, which makes sense, because the payload is pretty large.

**Comment by pumazi** [comment]
We'll likely need to increase the timeout period from 600s to 1200s, which is what the legacy software is defined at. 

``.first_byte_timeout = 600s;`` vs ``.first_byte_timeout = 1200s;``

But I'm thinking that likely isn't even enough because this is still a relatively small payload in the scheme of things.

**Comment by pumazi** [comment]
Chances are we are bottlenecked at the file system write part of accepting the publication. We may need to create in-memory objects that have the pathlib.Path interface. But let's first start with a higher timeout.

**Comment by pumazi** [comment]
Looks like an easy "bump up the settings" solution is not going to work. The app will likely need to be adjusted to give a response ASAP. We can do that right after verifying the payload is a valid zip file. It should be possible to use the WSGI iterative response.

**Comment by pumazi** [comment]
Essentially the root of the problem is this absurdly large payload we expect the system to process. Ideally we should break this up into several requests, but that will be a lot more work to do. But the current implementation is still the best course when considering speed of development and value.

We will need to make the publishing async. We'll be doing this a little sooner than I anticipated, but if it must be done, so be it. This would largely leave the implemented bits as they are and sprinkle in several state updating funcs. The existing funcs would be wrapped in a celery task.

**Comment by reedstrm** [comment]
Hmm, Would it help at all to take varnish out of the process for now? Talk to the raw server port, where we can control the timeouts to be essentially infinite. Just short term, longer is as you say, something async.

**Comment by pumazi** [comment]
For sure! I had put something to this effect in a message to Bey:
> We do have something that works, but only for really small edits. And we could work around the current issue by side stepping Varnish (caching service). So, it's not that the current implementation is broken, but that it's limited by the production configuration.

Exposing the service isn't the prettiest thing to do, but for testing purposes it would do.

**Comment by reedstrm** [comment]
Was wondering why we never saw this problem w/ authoring/publishing, since we send a big zip there, too, but that was a direct port connection, server-to-server.

**Comment by pumazi** [comment]
After talking with @Bkblodget about this, we'll work on the short-term solution to side-step Varnish. She is going to put together a story for a longer-term approach. In the near-term we'll probably work to get publishing async, which may open us back up to fitting into a production-worthy solution.

I'll followup by linking cnx-deploy PRs to this issue and close once the command successfully goes through.
