### ISSUE TITLE
'make test' fails if local postgresql is running

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-press#79]
Seems the docker image for cnx-db (which used for isolation?) fails to launch if there is a local instance of postgresql running, listening on port 5432 (the standard port)

**Comment by reedstrm** [comment]
Note this seems to only be true on first launch (docker-compose of the image?) After that, it can be run.

**Comment by reedstrm** [comment]
(rewrite3) reedstrm@sensei:~/src/rewrite3/cnx-press (issue-75-new-uuid)$ make test
docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm web bin/test  
Creating network "cnxpress_default" with the default driver
Pulling db (openstax/cnx-db:2.0.1)...
2.0.1: Pulling from openstax/cnx-db
f2b6b4884fc8: Pull complete
1202af1fe3ec: Pull complete
347c23494b41: Pull complete
552490497874: Pull complete
c40f61f0480d: Pull complete
ea2c81f83835: Pull complete
4edaff876fef: Pull complete
02d9d296d333: Pull complete
0ee950da2956: Pull complete
8e5e8f5f87fb: Pull complete
14b436dbd0fe: Pull complete
fcebc2679342: Pull complete
d3a0af7e17f0: Pull complete
90268b21b42b: Pull complete
fe8a0fdcdd2e: Pull complete
da420776c844: Pull complete
fc5d57669abb: Pull complete
cfef414f5470: Pull complete
a9d6e54b6e35: Pull complete
6da03de31081: Pull complete
Digest: sha256:21510e2060e0f195eaa3ca00c124471fc93f493daca87ff2cb4f87172ed13639
Status: Downloaded newer image for openstax/cnx-db:2.0.1
Creating cnxpress_db_1

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint cnxpress_db_1 (90003ffd397f862cc21c4fb9cd28db9a6a62a5b4391cd47e53b4f6d2bda7f242): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Makefile:100: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by reedstrm** [comment]
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint cnxpress_db_1 (4b70b6ab104f938b1be73fec249333d1144c9a33bc861b520531d8f21f837e54): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Makefile:100: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by reedstrm** [comment]
(rewrite3) reedstrm@sensei:~/src/rewrite3/cnx-press (master)$ make test
docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm web bin/test  
Starting cnxpress_db_1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

+ echo 'Postgres is unavailable - sleeping'
Postgres is unavailable - sleeping
+ sleep 1
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
+ echo 'Postgres is up - continuing execution'
Postgres is up - continuing execution
+ python -m pytest --strict
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
======================================== test session starts =========================================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app, inifile: setup.cfg
plugins: cov-2.5.1, cnx-litezip-1.3.1, cnx-db-2.0.1
collected 33 items                                                                                   

tests/functional/views/test_legacy_publishing.py::test_publishing_invalid_zip PASSED           [  3%]
tests/functional/views/test_legacy_publishing.py::test_publishing_invalid_revision_litezip PASSED [  6%]
tests/functional/views/test_legacy_publishing.py::test_publishing_revision_litezip PASSED      [  9%]
tests/functional/views/test_ping.py::test_successful_ping PASSED                               [ 12%]
tests/unit/test_config.py::test_discover_set_with_env_var PASSED                               [ 15%]
tests/unit/test_config.py::test_discover_set_without_env_var_or_default PASSED                 [ 18%]
tests/unit/test_config.py::test_discover_set_with_default PASSED                               [ 21%]
tests/unit/test_config.py::test_discover_set_witout_env_var_and_keeps_existing PASSED          [ 24%]
tests/unit/test_config.py::test_discover_set_with_env_var_and_existing PASSED                  [ 27%]
tests/unit/test_config.py::test_discover_set_with_env_var_and_modifier PASSED                  [ 30%]
tests/unit/test_logging.py::test_init PASSED                                                   [ 33%]
tests/unit/test_logging.py::test_init_with_debug PASSED                                        [ 36%]
tests/unit/test_logging.py::test_includeme PASSED                                              [ 39%]
tests/unit/test_logging.py::test_request_id PASSED                                             [ 42%]
tests/unit/test_logging.py::test_request_log PASSED                                            [ 45%]
tests/unit/test_publishing.py::test_persist_file_to_filesystem PASSED                          [ 48%]
tests/unit/test_publishing.py::test_expand_zip PASSED                                          [ 51%]
tests/unit/test_publishing.py::test_discover_content_dir PASSED                                [ 54%]
tests/unit/test_publishing.py::test_discover_content_dir_with_multiple_dirs PASSED             [ 57%]
tests/unit/test_publishing.py::test_discover_content_dir_with_no_dirs PASSED                   [ 60%]
tests/unit/test_raven.py::test_tween_without_error PASSED                                      [ 63%]
tests/unit/test_raven.py::test_tween_with_error PASSED                                         [ 66%]
tests/unit/test_raven.py::test_includeme PASSED                                                [ 69%]
tests/unit/legacy_publishing/test_collection.py::test_publish_legacy_book PASSED               [ 72%]
tests/unit/legacy_publishing/test_litezip.py::test_publish_litezip PASSED                      [ 75%]
tests/unit/legacy_publishing/test_module.py::test_publish_revision_to_legacy_page PASSED       [ 78%]
tests/unit/legacy_publishing/test_utils.py::test_replace_id_and_version PASSED                 [ 81%]
tests/unit/parsers/test_collection.py::test_parse_collection_metadata PASSED                   [ 84%]
tests/unit/parsers/test_collection.py::test_parse_colletion_metdata_without_print_style PASSED [ 87%]
tests/unit/parsers/test_collection.py::test_parse_colletion_metdata_with_print_style PASSED    [ 90%]
tests/unit/parsers/test_common.py::test_parse_common_properties_without_abstract PASSED        [ 93%]
tests/unit/parsers/test_common.py::test_parse_with_cnxml_abstract PASSED                       [ 96%]
tests/unit/parsers/test_module.py::test_parse_module_metadata PASSED                           [100%]

----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                                    Stmts   Miss  Cover
-----------------------------------------------------------
press/__init__.py                           0      0   100%
press/config.py                            31      0   100%
press/legacy_publishing/__init__.py         3      0   100%
press/legacy_publishing/collection.py      27      0   100%
press/legacy_publishing/litezip.py         30      0   100%
press/legacy_publishing/module.py          27      0   100%
press/legacy_publishing/utils.py           12      0   100%
press/logging.py                           17      0   100%
press/main.py                               1      0   100%
press/models.py                             4      0   100%
press/parsers/__init__.py                   2      0   100%
press/parsers/collection.py                11      0   100%
press/parsers/common.py                    31      0   100%
press/parsers/module.py                     4      0   100%
press/publishing.py                        31      0   100%
press/raven.py                             15      0   100%
press/views/__init__.py                    14      0   100%
press/views/legacy_publishing.py           29      0   100%
press/views/ping.py                         4      0   100%
-----------------------------------------------------------
TOTAL                                     293      0   100%


===================================== 33 passed in 10.53 seconds =====================================
+ python -m coverage html
+ '[' '' = true ']'
(rewrite3) reedstrm@sensei:~/src/rewrite3/cnx-press (master)$ sudo systemctl start postgresql(rewrite3) reedstrm@sensei:~/src/rewrite3/cnx-press (master)$ make test
docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm web bin/test  
+ python -c 'import os, psycopg2 as p; dsn = os.environ['\''DB_SUPER_URL'\''].rsplit('\''/'\'', 1)[0] + '\''/postgres'\'';p.connect(dsn)'
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
+ echo 'Postgres is up - continuing execution'
Postgres is up - continuing execution
+ python -m pytest --strict
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
======================================== test session starts =========================================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app, inifile: setup.cfg
plugins: cov-2.5.1, cnx-litezip-1.3.1, cnx-db-2.0.1
collected 33 items                                                                                   

tests/functional/views/test_legacy_publishing.py::test_publishing_invalid_zip PASSED           [  3%]
tests/functional/views/test_legacy_publishing.py::test_publishing_invalid_revision_litezip PASSED [  6%]
tests/functional/views/test_legacy_publishing.py::test_publishing_revision_litezip PASSED      [  9%]
tests/functional/views/test_ping.py::test_successful_ping PASSED                               [ 12%]
tests/unit/test_config.py::test_discover_set_with_env_var PASSED                               [ 15%]
tests/unit/test_config.py::test_discover_set_without_env_var_or_default PASSED                 [ 18%]
tests/unit/test_config.py::test_discover_set_with_default PASSED                               [ 21%]
tests/unit/test_config.py::test_discover_set_witout_env_var_and_keeps_existing PASSED          [ 24%]
tests/unit/test_config.py::test_discover_set_with_env_var_and_existing PASSED                  [ 27%]
tests/unit/test_config.py::test_discover_set_with_env_var_and_modifier PASSED                  [ 30%]
tests/unit/test_logging.py::test_init PASSED                                                   [ 33%]
tests/unit/test_logging.py::test_init_with_debug PASSED                                        [ 36%]
tests/unit/test_logging.py::test_includeme PASSED                                              [ 39%]
tests/unit/test_logging.py::test_request_id PASSED                                             [ 42%]
tests/unit/test_logging.py::test_request_log PASSED                                            [ 45%]
tests/unit/test_publishing.py::test_persist_file_to_filesystem PASSED                          [ 48%]
tests/unit/test_publishing.py::test_expand_zip PASSED                                          [ 51%]
tests/unit/test_publishing.py::test_discover_content_dir PASSED                                [ 54%]
tests/unit/test_publishing.py::test_discover_content_dir_with_multiple_dirs PASSED             [ 57%]
tests/unit/test_publishing.py::test_discover_content_dir_with_no_dirs PASSED                   [ 60%]
tests/unit/test_raven.py::test_tween_without_error PASSED                                      [ 63%]
tests/unit/test_raven.py::test_tween_with_error PASSED                                         [ 66%]
tests/unit/test_raven.py::test_includeme PASSED                                                [ 69%]
tests/unit/legacy_publishing/test_collection.py::test_publish_legacy_book PASSED               [ 72%]
tests/unit/legacy_publishing/test_litezip.py::test_publish_litezip PASSED                      [ 75%]
tests/unit/legacy_publishing/test_module.py::test_publish_revision_to_legacy_page PASSED       [ 78%]
tests/unit/legacy_publishing/test_utils.py::test_replace_id_and_version PASSED                 [ 81%]
tests/unit/parsers/test_collection.py::test_parse_collection_metadata PASSED                   [ 84%]
tests/unit/parsers/test_collection.py::test_parse_colletion_metdata_without_print_style PASSED [ 87%]
tests/unit/parsers/test_collection.py::test_parse_colletion_metdata_with_print_style PASSED    [ 90%]
tests/unit/parsers/test_common.py::test_parse_common_properties_without_abstract PASSED        [ 93%]
tests/unit/parsers/test_common.py::test_parse_with_cnxml_abstract PASSED                       [ 96%]
tests/unit/parsers/test_module.py::test_parse_module_metadata PASSED                           [100%]

----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                                    Stmts   Miss  Cover
-----------------------------------------------------------
press/__init__.py                           0      0   100%
press/config.py                            31      0   100%
press/legacy_publishing/__init__.py         3      0   100%
press/legacy_publishing/collection.py      27      0   100%
press/legacy_publishing/litezip.py         30      0   100%
press/legacy_publishing/module.py          27      0   100%
press/legacy_publishing/utils.py           12      0   100%
press/logging.py                           17      0   100%
press/main.py                               1      0   100%
press/models.py                             4      0   100%
press/parsers/__init__.py                   2      0   100%
press/parsers/collection.py                11      0   100%
press/parsers/common.py                    31      0   100%
press/parsers/module.py                     4      0   100%
press/publishing.py                        31      0   100%
press/raven.py                             15      0   100%
press/views/__init__.py                    14      0   100%
press/views/legacy_publishing.py           29      0   100%
press/views/ping.py                         4      0   100%
-----------------------------------------------------------
TOTAL                                     293      0   100%


===================================== 33 passed in 9.12 seconds ======================================
+ python -m coverage html
+ '[' '' = true ']'
(rewrite3) reedstrm@sensei:~/src/rewrite3/cnx-press (master)$

**Comment by reedstrm** [comment]
Correction - it leaves a 'docker-proxy' service running holding port 5432. So, conflicts w/ standard DB
